# Generated by Django 5.1.6 on 2025-03-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_formdata_message_formdata_age_formdata_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
