# Generated by Django 5.1.6 on 2025-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='message',
        ),
        migrations.AddField(
            model_name='formdata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='goal',
            field=models.CharField(blank=True, choices=[('Gain', 'Gain'), ('Lose', 'Lose'), ('Fit', 'Fit')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
