# Generated by Django 5.1.6 on 2025-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_formdata_password_alter_formdata_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preference', models.CharField(max_length=50)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('symptoms', models.JSONField(default=list)),
                ('food_frequency', models.JSONField(default=dict)),
                ('water_intake', models.CharField(max_length=50)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('extra_symptoms', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
