# Generated by Django 5.1.6 on 2025-03-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_nutritionassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionassessment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='api.formdata'),
        ),
    ]
