# Generated by Django 5.1.6 on 2025-03-12 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_dietary_preference_nutritionassessment_dietarypreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionassessment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='api.formdata', unique=True),
        ),
    ]
