# Generated by Django 5.1.6 on 2025-03-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_nutritionassessment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
