# Generated by Django 5.1.6 on 2025-03-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_formdata_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
