# Generated by Django 5.1.6 on 2025-04-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_whatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalDeficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deficiencies', models.JSONField()),
                ('percentages', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deficiency', to='api.formdata')),
            ],
        ),
    ]
