# Generated by Django 5.1.6 on 2025-04-04 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_nutritionaldeficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_calories', models.CharField(max_length=20)),
                ('calories_taken', models.CharField(default='0', max_length=20)),
                ('protein_goal', models.CharField(max_length=20)),
                ('protein_taken', models.CharField(default='0', max_length=20)),
                ('fat_goal', models.CharField(max_length=20)),
                ('fat_taken', models.CharField(default='0', max_length=20)),
                ('carbs_goal', models.CharField(max_length=20)),
                ('carbs_taken', models.CharField(default='0', max_length=20)),
                ('fiber_goal', models.CharField(max_length=20)),
                ('fiber_taken', models.CharField(default='0', max_length=20)),
                ('micro1_name', models.CharField(max_length=50)),
                ('micro1_goal', models.CharField(max_length=20)),
                ('micro1_taken', models.CharField(default='0', max_length=20)),
                ('micro2_name', models.CharField(max_length=50)),
                ('micro2_goal', models.CharField(max_length=20)),
                ('micro2_taken', models.CharField(default='0', max_length=20)),
                ('micro3_name', models.CharField(max_length=50)),
                ('micro3_goal', models.CharField(max_length=20)),
                ('micro3_taken', models.CharField(default='0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_goals', to='api.formdata')),
            ],
        ),
    ]
