# Generated by Django 5.1.6 on 2025-04-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_nutritionalgoal_carbs_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalgoal',
            name='carbs_goal',
            field=models.CharField(default='300g', max_length=20),
        ),
        migrations.AlterField(
            model_name='nutritionalgoal',
            name='fat_goal',
            field=models.CharField(default='75g', max_length=20),
        ),
        migrations.AlterField(
            model_name='nutritionalgoal',
            name='fiber_goal',
            field=models.CharField(default='25g', max_length=20),
        ),
        migrations.AlterField(
            model_name='nutritionalgoal',
            name='goal_calories',
            field=models.CharField(default='2520', max_length=20),
        ),
        migrations.AlterField(
            model_name='nutritionalgoal',
            name='micro1_goal',
            field=models.CharField(default='20mg/day', max_length=20),
        ),
        migrations.AlterField(
            model_name='nutritionalgoal',
            name='micro1_name',
            field=models.CharField(blank=True, default='iron', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionalgoal',
            name='micro2_goal',
            field=models.CharField(default='2mcg/day', max_length=20),
        ),
        migrations.AlterField(
            model_name='nutritionalgoal',
            name='micro2_name',
            field=models.CharField(blank=True, default='vitaminb12', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionalgoal',
            name='micro3_goal',
            field=models.CharField(default='400mcg/day', max_length=20),
        ),
        migrations.AlterField(
            model_name='nutritionalgoal',
            name='micro3_name',
            field=models.CharField(blank=True, default='folate', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionalgoal',
            name='protein_goal',
            field=models.CharField(default='30g', max_length=20),
        ),
    ]
